### PR TITLE
Rebuild nerdfont (again ;p)

### PR DESCRIPTION
**Pull request by NiLuJe**
This time, replace the backspace MDI glyph with the outline variant from
the latest MDI package.

re: https://github.com/koreader/koreader/pull/5639

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader-fonts/9)

### CODE REVIEW

**Comment by NiLuJe** [comment]
This simply involves getting the latest TTF webfont from MDI, copy/pasting the glyph in nerdfont's copy in src/glyphs, and Bob's your uncle.

I, err, may also have tweaked its centering once Noto-ized (glyph's baseline @ -50).

**Comment by NiLuJe** [comment]
Even if we don't end up using it, it can't hurt, since the old filled-in variant is pretty awful anyway ;).

**Comment by Frenzie** [comment]
Sounds a bit labor intensive. Did you automate it? ;-)

**Comment by NiLuJe** [comment]
Not really, but it's pretty quick in FF ;p.

The most annoying was getting it to actually render centered, since just matching the font's baseline didn't do the trick ;).

**Pull request merged**
