### PR TITLE
Update Noto & FreeFont

### PR DESCRIPTION
**Pull request by NiLuJe**
Also switch FreeFont to the OTF variant (without changing the file extension to avoid duplicates when upgrading).

Should fix https://github.com/koreader/koreader/issues/4707

### CODE REVIEW

**Comment by Frenzie** [comment]
Actually MuPDF does most RTL basics correctly in EPUB/FB2. :-P

**Comment by NiLuJe** [comment]
s/FreeFont/FontForge/ -_-".

**Comment by NiLuJe** [comment]
Can't really judge, but at least the Arabic kerning tables are there and appear to be populated.

**Comment by NiLuJe** [comment]
The comment dates back to 2012, there's a fair chance FontForge got fixed since then?

**Comment by Frenzie** [comment]
That chance could be very real in that case. :-D

**Comment by NiLuJe** [comment]
(Rebased to squash the two FreeFont commits together, so we can merge this as a rebase).

**Comment by NiLuJe** [comment]
...

s/FontConfig/FontForge/

*sigh*

:D

**Pull request merged**
