### PR TITLE
Update FreeFont

### PR DESCRIPTION
**Pull request by NiLuJe**
r4240, built manually (Force Encoding > Unicode Full).
As usual, actually a CFF renamed to .ttf to ease backwards compat.

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader-fonts/14)

### CODE REVIEW

**Comment by NiLuJe** [comment]
I can delay this post #13, just wanted to have the files around while we're messing with fonts ;).

**Comment by ezdiy** [comment]
Go ahead and push it. Its likely i'll mess with it further (really the mupdf thing will be reliably buildable in few days at best, so ...)

**Comment by Frenzie** [comment]
@NiLuJe Don't forget to bump base so as not to break the next nightly build with its shallow fetch.

**Comment by NiLuJe** [comment]
@Frenzie: Ah, thanks for reminding me ;p. Will do later tonight!

**Pull request merged**
