### PR TITLE
Noto Sans Bengali UI for Bengali support

### PR DESCRIPTION
**Pull request by uroybd**
This is to add Bengali Rendering support in KOReader. I'm adding this based on the discussion here: koreader/koreader#8887

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader-fonts/16)

### CODE REVIEW

**Comment by poire-z** [comment]
For reference, can you tell / point to a url where this font file comes from.
From your own Android, from Google noto site, from Noto github... ?
They may not be all the same, nor is the newest the best (for CJK, we use the Google noto site one, the Noto github ones, which are newest, have been exhibiting some strange bugs).

**Comment by uroybd** [comment]
I took this font from Google Font Early Access Repository.

Here's the css: https://fonts.googleapis.com/earlyaccess/notosansbengaliui.css

I chose the 'UI' version over the normal version found in google fonts for its crispiness.

**Comment by NiLuJe** [comment]
I'd take a real font over the Google web font API stuff ;). (The web font variants are often weirdly packaged because of space concerns).

Check the goolgefonts GitHub repo.

**Comment by uroybd** [comment]
> I'd take a real font over the Google web font API stuff ;). (The web font variants are often weirdly packaged because of space concerns).
> 
> Check the goolgefonts GitHub repo.

Changed the font. Now using from https://github.com/googlefonts/noto-fonts/blob/main/hinted/ttf/NotoSansBengaliUI/NotoSansBengaliUI-Regular.ttf

**Comment by poire-z** [comment]
I don't remember: do we favor hinted or unhinted ?

**Comment by Frenzie** [comment]
Unhinted I guess? Not really sure either though.

**Comment by uroybd** [comment]
I think you prefer hinted. Devanagari font used in this repo is hinted.

I prefer hinted too. For crisper reading, hints are necessary. Fonts with hinting looks better than auto-generated hints.

**Comment by NiLuJe** [comment]
The higher the DPI, the less meaningful it becomes ;). Plus, hints might not be hand-crafted, but auto-generated by ttfautohint, which is just how we render fonts on our end anyway.

That said, we still prefer hinted fonts anyway, because they (generally) can't be worse, and the impact on code size is barely visible ;).

**Comment by poire-z** [comment]
(^ letting you merge this if you're satisfied :)

**Comment by poire-z** [comment]
@NiLuJe : does that :+1: means you're satisfied and this can be merged ? Or that you'll think about it later ?

**Comment by NiLuJe** [comment]
Oops, right, sorry.

It indeed meant 'ACK', and that I was going to merge it myself, and then I... forgot :D.

**Pull request merged**
